<?php

/**
 * @file
 * Hooks and utility functions for Commerce Stock History.
 */

/**
 * Implements hook_menu().
 */
function commerce_stock_history_menu() {
  // @TODO: Is this necesary or can we use a view?
  $items['admin/commerce/products/%commerce_product/stock-history'] = array(
    'title' => 'Stock history',
    'page callback' => 'commerce_stock_history_view_page',
    'access arguments' => array('access content'),
    'file path' => drupal_get_path('module', 'commerce_stock_history') . '/includes',
    'file' => 'commerce_stock_history.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
}

/**
 * Implements hook_permission().
 */
function commerce_stock_history_permission() {
  return array(
    'view commerce stock history' => array(
      'title' => t('View stock history'),
    ),
  );
}

/**
 * Implements hook_entity_info().
 */
function commerce_stock_history_entity_info() {
  $info = array();

  $info['commerce_stock_history'] = array(
    'label' => t('Stock history'),
    'base table' => 'commerce_stock_history',
    'entity keys' => array(
      'id' => 'id',
      'label' => 'message',
    ),
    'module' => 'commerce_stock_history',
    'entity class' => 'Entity',
    'controller class' => 'EntityAPIController',
    'views controller class' => 'EntityDefaultViewsController',
  );

  return $info;
}

/**
 * Implements hook_entity_property_info().
 */
function commerce_stock_history_entity_property_info() {
  $info = array();
  $properties = &$info['node']['properties'];

  $properties['id'] = array(
    'label' => t('Stock history ID'),
    'description' => t('The unique ID for the stock history entry.'),
    'type' => 'integer',
  );

  $properties['message'] = array(
    'label' => t('Stock history message'),
    'description' => t('The stock history message.'),
    'type' => 'text',
  );

  $properties['product_id'] = array(
    'label' => t('Stock history product ID'),
    'description' => t('The ID of the product that the stock adjustment was made on.'),
    'type' => 'integer',
  );

  $properties['quantity'] = array(
    'label' => t('Stock history quantity'),
    'description' => t("The amount that the product's stock as adjusted by."),
    'type' => 'integer',
  );

  $properties['uid'] = array(
    'label' => t('Stock history user'),
    'description' => t('The ID of the user who created the stock history entity.'),
    'type' => 'integer',
  );

  $properties['created'] = array(
    'label' => t('Stock history creation'),
    'description' => t('The time that the stock history entity was created.'),
    'type' => 'integer',
  );

  return $info;
}
